### ISSUE TITLE
Can't get addon to show in extensions to install.

### ISSUE THREAD

**Issue by edster** [websemantics/builder-extension#1]
I placed the code in addons/default/websemantics/entity_builder-extension as per the readme but I can't get it to load in the backend to install.(my app instance is default)

**Comment by websemantics** [comment]
That's interesting, .. do you get an error? can you see it listed under admin/addons/extensions?

**Comment by websemantics** [comment]
Also make sure the extension folder has read permission

**Comment by edster** [comment]
You know what, I'm an idiot. I thought I made my reference default.

Moved it to the right reference in addons and it is showing up......sorry......
