### ISSUE TITLE
Bug on windows machine

### ISSUE THREAD

**Issue by dutch2g** [websemantics/builder-extension#13]
I get an error installing the builder on a **windows10 machine**

composer require websemantics/builder-extension

[ErrorException] ZipArchive::extractTo(C:\pyrocms/vendor/composer/4d589e26/websemantics-builder-extension-f694a92\resources\stubs\entity\code\Http\Controller\Admin/**{{entity_name|str_plural}}**Controller.php): failed to open stream: Invalid argument

**Comment by edster** [comment]
Troubleshooted this just now, can't use the `|` as a file or folder name
