### ISSUE TITLE
[Feature]: Add findBySlug function into repositories

### ISSUE THREAD

**Issue by edster** [websemantics/builder-extension#20]
If you can add a findBySlug to the respoiroty that would be great, use it alot and would be nice to not always having to add it in.

```
/**
     * Find a stream by it's slug.
     *
     * @param $slug
     * @return null|StreamRepositoryInterface
     */
    public function findBySlug($slug)
    {
        return $this->model->where('slug', $slug)->first();
    }
```

**Comment by websemantics** [comment]
Looking at the code, there's something more generic but quite similar

```php
$repo->findBy('slug', $slug);
```

To use with `id`, etc
```php
$repo->findBy('id', $id);
```

Not too far from suggested code. Will close but feel free to re-open if you still need `findBySlug` method specifically.

Ps. apologies for such a poor response time! I've been taken away from Pyro world over the last while for work related projects,
