### ISSUE TITLE
install problem websemantics/builder-extension

### ISSUE THREAD

**Issue by ghost** [websemantics/builder-extension#25]
`jubayed@localhost /srv/project/pyrocms % composer require websemantics/builder-extension
Using version ^1.1 for websemantics/builder-extension
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - websemantics/builder-extension 1.1.2 requires nikic/php-parser ~2.0 -> satisfiable by nikic/php-parser[2.x-dev, v2.0.0, v2.0.0alpha1, v2.0.0beta1, v2.0.1, v2.1.0, v2.1.1] but these conflict with your requirements or minimum-stability.
    - websemantics/builder-extension 1.1.1 requires nikic/php-parser ~2.0 -> satisfiable by nikic/php-parser[2.x-dev, v2.0.0, v2.0.0alpha1, v2.0.0beta1, v2.0.1, v2.1.0, v2.1.1] but these conflict with your requirements or minimum-stability.
    - websemantics/builder-extension 1.1.0 requires nikic/php-parser ~2.0 -> satisfiable by nikic/php-parser[2.x-dev, v2.0.0, v2.0.0alpha1, v2.0.0beta1, v2.0.1, v2.1.0, v2.1.1] but these conflict with your requirements or minimum-stability.
    - Installation request for websemantics/builder-extension ^1.1 -> satisfiable by websemantics/builder-extension[1.1.0, 1.1.1, 1.1.2].

Installation failed, reverting ./composer.json to its original content.
composer require websemantics/builder-extension  5.83s user 0.49s system 48% cpu 12.936 total
`

**Comment by ThinkGraphical** [comment]
I'm still getting that same error too, i can only give you the quickfix:

Add the following manually to your composer.json
```
"require": [
    ...
    "websemantics/builder-extension": "dev-master"
],
```

Notice the "dev-master" not the "1.1.2".

**Comment by ghost** [comment]
thx
