### ISSUE TITLE
Issues when creating a admin skin

### ISSUE THREAD

**Issue by ThinkGraphical** [websemantics/builder-extension#26]
When generating an admin skin (`php artisan make:addon vendor.skin.sunshine`),
I've had to correct 3 things to get it working:

- In config->skin.php had to change `'import' => __DIR__ . '/../scss/skin.scss',` to `'import' => __DIR__ . '/../scss/`

- In resources->scss move the _variables/skin scss files into a subfolder 'skin' (the generator places the files in de scss root, while the LoadThemeVariables.php handle function expects them to be in a 'skin' subfolder

- Remove the imports in skin.scss

At this point it worked, i was able to change the color for $toggle-bg, etc...

Following issue i encountered was when changing $brand-primary, $brand-success, etc...

![screen shot 2017-01-04 at 10 14 21](https://cloud.githubusercontent.com/assets/1651789/21637305/ae25c6bc-d266-11e6-8596-21efdd8101ae.png)

Here you would expect the "new widget" button to be purple/pink (btn-success => brand-success) & the "recent news" to be orange (card-primary => brand-primary).

I suspect there's a issue with the parsing order of the variables.

**Comment by ThinkGraphical** [comment]
I just noticed that the last issue is the 'fault' of pyrocms itself,
in `core/pyrocms/pyrocms-theme/scss/theme/_variables` brand-primary, etc... aren't defined with !default which prevents us from overwriting in a later stage.

**Comment by websemantics** [comment]
Went to open an issue but you've already done so, 
https://github.com/pyrocms/pyrocms-theme/pull/17/commits

Fixed the [skin template](https://github.com/pyrocms-templates/default-skin/releases/tag/0.1.1), (thanks for heads up),  just make sure to use `--force` to download latest template when use `make:addon` command,
