### ISSUE TITLE
String_loader is depreciated

### ISSUE THREAD

**Issue by edster** [websemantics/builder-extension#30]
https://github.com/websemantics/builder-extension/pull/29

Pull request has an issue after this change. Not sure if unrelated but havn't been able to find a fix for it.
```
C:\Sites\martello_group\core\websemantics\builder-extension\src\Support\TwigParser.php
   * @param UrlGenerator $url
   * @param Engine       $parser
   * @param Request      $request
   */
  public function __construct()
  {
    $this->twig = new \Twig_Environment(new \Twig_Loader_Array());
    $this->twig->addExtension(new TwigExtension());
  }
 
  /**
   * Parse data into the content
   *
   * @param  string $content
   * @param  array $data
   * @return string
   */
  public function parse($content, $data = [])
  {
    return $this->twig->render($content, $data);
  }
}
 
Arguments
"Http"
array:7 [▶]
```

**Comment by websemantics** [comment]
Hi @edster and thanks for the PR, 

Haven't been using the Builder / Pyro for quit awhile :/ ...  However, looking into the [link](https://github.com/twigphp/Twig/pull/1641) you provided it seems there's an extra step of creating a template that's missing,

So the `parse` function should now have

```php
public function parse($content, $data = [])
  {
    $template = $env->createTemplate($content);
    return $this->twig->render($template, $data);
  }
```

I haven't tested this so be careful :)

**Comment by edster** [comment]
Thanks @websemantics, that got me farther along, I figured there was something missing there.

Ends up throwing Illegal offset type in isset or empty afterwards.

Not sure how this all works xD, might be a bug https://github.com/twigphp/Twig/issues/2546
